### PR TITLE
remove envproxy references from chart

### PR DESCRIPTION
**Pull request by f0ssel**

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]
LGTM. We can remove the entire Ingress object now too!

**Comment by deansheather** [comment]
We can't remove the ingress object because it'll break customers that use cert-manager with ingress annotations, which the docs have recommended in the recent past

**Review by deansheather — APPROVED** [review]

**Comment by jawnsy** [comment]
We also need an ingress because LoadBalancer controllers are not a mandatory part of Kubernetes, so not every cluster has them. The clouds all have load balancer controllers but bare metal systems might not, which is why the [MetalLB documentation](https://metallb.universe.tf/) says:

>Kubernetes does not offer an implementation of network load balancers (Services of type LoadBalancer) for bare-metal clusters. The implementations of network load balancers that Kubernetes does ship with are all glue code that calls out to various IaaS platforms (GCP, AWS, Azure…). If you’re not running on a supported IaaS platform (GCP, AWS, Azure…), LoadBalancers will remain in the “pending” state indefinitely when created.

**Comment by f0ssel** [comment]
Yeah I think keeping an optional, dumb one is a happy medium

**Pull request merged**
